import type { Metadata } from 'next';
import './globals.css';
import { DarkModeProvider } from '@/context/DarkModeContext';

export const metadata: Metadata = {
  title: 'Into the Math',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
}
